* ChangeLog
** 2016/03/07 created hello-world webapp
** 2016/03/07 checked yada library but not enough documentation avaiable at this time
** 2016/03/08 investigated component for managing lifecycle of the app
** 2016/03/09 created project from duct template as it already set up the component structure
** 2016/03/10 created endpoint to get some basic configurations with schema validation, different from every environment
** 2016/03/11 played with EDN data structure validation with Schema. Not sure if Schema is the library I'm looking for.
** 2016/03/12 reading facebook's configuration system paper... brutal!
** 2016/03/13 reading facebook's configuration system paper... brutal!
** 2016/03/14 playing with clojure git lib
** 2016/03/15 playing with clojure git lib. mood :
** 2016/03/16 retrieving files from git repository. very fluffy. getting weird login errors with docker gitlab image.
** 2016/03/18 more on clj-jgit lib. no clue how git-pull vs git-fetch. trial-and-error mode.
** 2016/03/19 quite frustrated integrating timbre logger. main issue: lack of knowledge how exactly component lib works and lack of updated examples. emacs-tail-revert-mode a bit slow.
** 2016/03/22 issues with clj-jgit when using strategy recursive resulted in: conflict

